# Generated by Django 5.2.4 on 2025-07-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PamUsers',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=160)),
                ('shell', models.CharField(default='/usr/bin/false', max_length=20)),
                ('status', models.CharField(blank=True, default='N', max_length=1)),
                ('uid', models.IntegerField()),
                ('gecos', models.CharField(blank=True, max_length=128, null=True)),
                ('homedir', models.CharField(blank=True, max_length=32, null=True)),
                ('lstchg', models.IntegerField(blank=True, default=-1)),
                ('min', models.IntegerField(blank=True, default=0)),
                ('max', models.IntegerField(blank=True, default=9999)),
                ('warn', models.IntegerField(blank=True, default=7)),
                ('inact', models.IntegerField(blank=True, default=-1)),
                ('expire', models.IntegerField(blank=True, default=-1)),
                ('flag', models.IntegerField(blank=True, default=-1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PamGroups',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('gid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, default='A', max_length=1)),
                ('password', models.CharField(blank=True, default='x', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Pam Groups',
                'verbose_name_plural': 'Pam Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='PamLog',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('rhost', models.TextField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='FtpPamUser',
            fields=[
            ],
            options={
                'verbose_name': 'FTP User',
                'verbose_name_plural': 'FTP User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pam.pamusers',),
        ),
        migrations.CreateModel(
            name='SftpPamUser',
            fields=[
            ],
            options={
                'verbose_name': 'SFTP User',
                'verbose_name_plural': 'SFTP User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pam.pamusers',),
        ),
        migrations.AddField(
            model_name='pamusers',
            name='gid',
            field=models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='pam.pamgroups'),
        ),
        migrations.CreateModel(
            name='PamGroupLists',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pam.pamusers')),
                ('gid', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='pam.pamgroups')),
            ],
            options={
                'db_table': 'grouplists',
                'constraints': [models.UniqueConstraint(fields=('username', 'gid'), name='unique_grouplists_username_gid')],
            },
        ),
    ]
