# Generated by Django 5.2.4 on 2025-07-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grouplists',
            table='pam_grouplists',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='pam_groups',
        ),
        migrations.AlterModelTable(
            name='log',
            table='pam_log',
        ),
        migrations.AlterModelTable(
            name='users',
            table='pam_users',
        ),
    ]
