# Generated by Django 5.2.4 on 2025-07-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0002_alter_grouplists_table_alter_groups_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
