# Generated by Django 5.2.4 on 2025-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0004_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
