# Generated by Django 5.2.4 on 2025-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam', '0005_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PamUsers',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(max_length=160)),
                ('shell', models.CharField(default='/usr/bin/false', max_length=20)),
                ('status', models.CharField(blank=True, default='N', max_length=1)),
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(default=5000)),
                ('gecos', models.CharField(blank=True, max_length=128, null=True)),
                ('homedir', models.CharField(blank=True, max_length=32, null=True)),
                ('lstchg', models.IntegerField(blank=True, default=-1)),
                ('min', models.IntegerField(blank=True, default=0)),
                ('max', models.IntegerField(blank=True, default=9999)),
                ('warn', models.IntegerField(blank=True, default=7)),
                ('inact', models.IntegerField(blank=True, default=-1)),
                ('expire', models.IntegerField(blank=True, default=-1)),
                ('flag', models.IntegerField(blank=True, default=-1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RenameModel(
            old_name='groups',
            new_name='PamGroups',
        ),
        migrations.RenameModel(
            old_name='log',
            new_name='PamLog',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='ftpUser',
        ),
        migrations.DeleteModel(
            name='sftpUser',
        ),
        migrations.AlterModelOptions(
            name='pamgroups',
            options={'verbose_name': 'Pam Groups', 'verbose_name_plural': 'Pam Groups'},
        ),
        migrations.AlterModelTable(
            name='grouplists',
            table='grouplists',
        ),
        migrations.AlterModelTable(
            name='pamgroups',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='pamlog',
            table='log',
        ),
        migrations.CreateModel(
            name='FtpPamUser',
            fields=[
            ],
            options={
                'verbose_name': 'FTP User',
                'verbose_name_plural': 'FTP User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pam.pamusers',),
        ),
        migrations.CreateModel(
            name='SftpPamUser',
            fields=[
            ],
            options={
                'verbose_name': 'SFTP User',
                'verbose_name_plural': 'SFTP User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pam.pamusers',),
        ),
    ]
